server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://172.30.100.64:30000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*" # Permitir todos los encabezados
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Cache-Control"
            allowCredentials: true
