server:
  port: 9001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: loan-request-service
          uri: lb://loan-request-service
          predicates:
            - Path=/loanRequest/**

        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/simulation/**

        - id: file-upload-service
          uri: lb://file-upload-service
          predicates:
            - Path=/fileUpload/**
            
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://172.30.100.64:30000" # Dominio del frontend local
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*" # Permitir todos los encabezados
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Cache-Control"
            allowCredentials: true
