server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
        
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: loan-request-service
          uri: lb://loan-request-service
          predicates:
            - Path=/loanRequest/**

        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/simulation/**

        - id: file-upload-service
          uri: lb://file-upload-service
          predicates:
            - Path=/fileUpload/**
            
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**







            
