server:
  port: 8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fees/**

        - id: group-discount-service
          uri: lb://group-discount-service
          predicates:
            - Path=/group-discount/**

        - id: file-upload-service
          uri: lb://file-upload-service
          predicates:
            - Path=/fileUpload/**
            
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/**

